/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author panjiad
 */
public class TicTac extends javax.swing.JFrame {

    static int currentPlayer = -1;
    static String playerBtn1 = "", playerBtn2 = "", playerBtn3 = "", playerBtn4 = "", playerBtn5 = "", playerBtn6 = "", playerBtn7 = "", playerBtn8 = "",playerBtn9 = "";
    static int btn1 = 0, btn2 = 0, btn3 = 0, btn4 = 0, btn5 = 0, btn6 = 0, btn7 = 0, btn8 = 0, btn9 = 0;

    /**
     * Creates new form TicTac
     */
    public TicTac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        hasilSuit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("Tic Tac Toe");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 20, 100, 21);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 90, 50, 50);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 90, 50, 50);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(260, 90, 50, 50);

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(80, 180, 50, 50);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(170, 180, 50, 50);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(260, 180, 50, 50);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(80, 270, 50, 50);

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(170, 270, 50, 50);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(260, 270, 50, 50);

        hasilSuit.setText("Menunggu hasil suit...");
        jPanel1.add(hasilSuit);
        hasilSuit.setBounds(20, 380, 151, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pagar_bg.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 50, 340, 308);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg_putih.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 380, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void kirim(String klue) {
        try {
            InetAddress ia = InetAddress.getByName("192.168.1.9");
            int Port = 2134;
            String s = klue;
            byte[] b = s.getBytes();
            DatagramPacket dp = new DatagramPacket(b, b.length, ia, Port);
            DatagramSocket sender = new DatagramSocket();
            sender.send(dp);
        } catch (IOException e) {
            System.out.println("salah");
        }
    }

    public static void setDisableButton() {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
    }

    public static void setEnable() {
        if (btn1 == 0) {
            jButton1.setEnabled(true);
        }
        if (btn2 == 0) {
            jButton2.setEnabled(true);
        }
        if (btn3 == 0) {
            jButton3.setEnabled(true);
        }
        if (btn4 == 0) {
            jButton4.setEnabled(true);
        }
        if (btn5 == 0) {
            jButton5.setEnabled(true);
        }
        if (btn6 == 0) {
            jButton6.setEnabled(true);
        }
        if (btn7 == 0) {
            jButton7.setEnabled(true);
        }
        if (btn8 == 0) {
            jButton8.setEnabled(true);
        }
        if (btn9 == 0) {
            jButton9.setEnabled(true);
        }
    }
    
    public static void clearBgBtn(){
        jButton1.setContentAreaFilled(false);
        jButton2.setContentAreaFilled(false);
        jButton3.setContentAreaFilled(false);
        jButton4.setContentAreaFilled(false);
        jButton5.setContentAreaFilled(false);
        jButton6.setContentAreaFilled(false);
        jButton7.setContentAreaFilled(false);
        jButton8.setContentAreaFilled(false);
        jButton9.setContentAreaFilled(false);
    }
    
    public static void menang(){
        if (playerBtn1.equals("x") && playerBtn2.equals("x") && playerBtn3.equals("x") ) {
            JOptionPane.showMessageDialog(null, "Player 1 Menang");
            setDisableButton();
        }
        else if (playerBtn1.equals("x") && playerBtn4.equals("x") && playerBtn7.equals("x") ) {
            JOptionPane.showMessageDialog(null, "Player 1 Menang");
            setDisableButton();
        }
        else if (playerBtn1.equals("x") && playerBtn5.equals("x") && playerBtn9.equals("x") ) {
            JOptionPane.showMessageDialog(null, "Player 1 Menang");
            setDisableButton();
        }
        else if (playerBtn3.equals("x") && playerBtn5.equals("x") && playerBtn7.equals("x") ) {
            JOptionPane.showMessageDialog(null, "Player 1 Menang");
            setDisableButton();
        }
        else if (playerBtn4.equals("x") && playerBtn5.equals("x") && playerBtn6.equals("x") ) {
            JOptionPane.showMessageDialog(null, "Player 1 Menang");
            setDisableButton();
        }
        else if (playerBtn7.equals("x") && playerBtn8.equals("x") && playerBtn9.equals("x") ) {
            JOptionPane.showMessageDialog(null, "Player 1 Menang");
            setDisableButton();
        }
        else if (playerBtn2.equals("x") && playerBtn5.equals("x") && playerBtn8.equals("x") ) {
            JOptionPane.showMessageDialog(null, "Player 1 Menang");
            setDisableButton();
        }
        else if (playerBtn3.equals("x") && playerBtn6.equals("x") && playerBtn9.equals("x") ) {
            JOptionPane.showMessageDialog(null, "Player 1 Menang");
            setDisableButton();
        }
        
        
        if (playerBtn1.equals("o") && playerBtn2.equals("o") && playerBtn3.equals("o") ) {
            JOptionPane.showMessageDialog(null, "Player 2 Menang");
            setDisableButton();
        }
        else if (playerBtn1.equals("o") && playerBtn4.equals("o") && playerBtn7.equals("o") ) {
            JOptionPane.showMessageDialog(null, "Player 2 Menang");
            setDisableButton();
        }
        else if (playerBtn1.equals("o") && playerBtn5.equals("o") && playerBtn9.equals("o") ) {
            JOptionPane.showMessageDialog(null, "Player 2 Menang");
            setDisableButton();
        }
        else if (playerBtn3.equals("o") && playerBtn5.equals("o") && playerBtn7.equals("o") ) {
            JOptionPane.showMessageDialog(null, "Player 2 Menang");
            setDisableButton();
        }
        else if (playerBtn4.equals("o") && playerBtn5.equals("o") && playerBtn6.equals("o") ) {
            JOptionPane.showMessageDialog(null, "Player 2 Menang");
            setDisableButton();
        }
        else if (playerBtn7.equals("o") && playerBtn8.equals("o") && playerBtn9.equals("o") ) {
            JOptionPane.showMessageDialog(null, "Player 2 Menang");
            setDisableButton();
        }
        else if (playerBtn2.equals("o") && playerBtn5.equals("o") && playerBtn8.equals("o") ) {
            JOptionPane.showMessageDialog(null, "Player 2 Menang");
            setDisableButton();
        }
        else if (playerBtn3.equals("o") && playerBtn6.equals("o") && playerBtn9.equals("o") ) {
            JOptionPane.showMessageDialog(null, "Player 2 Menang");
            setDisableButton();
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setDisableButton();
        clearBgBtn();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ImageIcon icon;

        if (currentPlayer == 0) {
            icon = new ImageIcon("src//silang.png");
            playerBtn1 = "x";
        } else {
            icon = new ImageIcon("src//lingkaran.png");
            playerBtn1 = "o";
        }
        jButton1.setIcon(icon);
        kirim("1");
        setDisableButton();
        btn1 = 1;
        menang();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ImageIcon icon;

        if (currentPlayer == 0) {
            icon = new ImageIcon("src//silang.png");
            playerBtn2 = "x";
        } else {
            icon = new ImageIcon("src//lingkaran.png");
            playerBtn2 = "o";
        }
        jButton2.setIcon(icon);
        kirim("2");
        setDisableButton();
        btn2 = 1;
        menang();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ImageIcon icon;

        if (currentPlayer == 0) {
            icon = new ImageIcon("src//silang.png");
            playerBtn3 = "x";
        } else {
            icon = new ImageIcon("src//lingkaran.png");
            playerBtn3 = "o";
        }
        jButton3.setIcon(icon);
        kirim("3");
        setDisableButton();
        btn3 = 1;
        menang();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ImageIcon icon;

        if (currentPlayer == 0) {
            icon = new ImageIcon("src//silang.png");
            playerBtn4 = "x";
        } else {
            icon = new ImageIcon("src//lingkaran.png");
            playerBtn4 = "o";
        }
        jButton4.setIcon(icon);
        kirim("4");
        setDisableButton();
        btn4 = 1;
        menang();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ImageIcon icon;

        if (currentPlayer == 0) {
            icon = new ImageIcon("src//silang.png");
            playerBtn5 = "x";
        } else {
            icon = new ImageIcon("src//lingkaran.png");
            playerBtn5 = "o";
        }
        jButton5.setIcon(icon);
        kirim("5");
        setDisableButton();
        btn5 = 1;
        menang();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ImageIcon icon;

        if (currentPlayer == 0) {
            icon = new ImageIcon("src//silang.png");
            playerBtn6 = "x";
        } else {
            icon = new ImageIcon("src//lingkaran.png");
            playerBtn6 = "o";
        }
        jButton6.setIcon(icon);
        kirim("6");
        setDisableButton();
        btn6 = 1;
        menang();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ImageIcon icon;

        if (currentPlayer == 0) {
            icon = new ImageIcon("src//silang.png");
            playerBtn7 = "x";
        } else {
            icon = new ImageIcon("src//lingkaran.png");
            playerBtn7 = "o";
        }
        jButton7.setIcon(icon);
        kirim("7");
        setDisableButton();
        btn7 = 1;
        menang();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ImageIcon icon;

        if (currentPlayer == 0) {
            icon = new ImageIcon("src//silang.png");
            playerBtn8 = "x";
        } else {
            icon = new ImageIcon("src//lingkaran.png");
            playerBtn8 = "o";
        }
        jButton8.setIcon(icon);
        kirim("8");
        setDisableButton();
        btn8 = 1;
        menang();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ImageIcon icon;

        if (currentPlayer == 0) {
            icon = new ImageIcon("src//silang.png");
            playerBtn9 = "x";
        } else {
            icon = new ImageIcon("src//lingkaran.png");
            playerBtn9 = "o";
        }
        jButton9.setIcon(icon);
        kirim("9");
        setDisableButton();
        btn9 = 1;
        menang();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTac().setVisible(true);
            }
        });
        

        try {
            byte[] buffer = new byte[100];
            DatagramPacket incoming = new DatagramPacket(buffer, buffer.length);
            DatagramSocket ds = new DatagramSocket(2134);
            String s = "";
            while (!s.equals("exit")) {
                ds.receive(incoming);
                s = new String(incoming.getData(), incoming.getOffset(), incoming.getLength());
                System.out.println(s);
                if (currentPlayer == -1) {
                    if (s.equals("home")) {
                        hasilSuit.setText("Pemain 2");
                        currentPlayer = 1;
                        jButton1.setEnabled(false);
                        jButton2.setEnabled(false);
                        jButton3.setEnabled(false);
                        jButton4.setEnabled(false);
                        jButton5.setEnabled(false);
                        jButton6.setEnabled(false);
                        jButton7.setEnabled(false);
                        jButton8.setEnabled(false);
                        jButton9.setEnabled(false);
                    } else {
                        hasilSuit.setText("Pemain 1");
                        currentPlayer = 0;
                        jButton1.setEnabled(true);
                        jButton2.setEnabled(true);
                        jButton3.setEnabled(true);
                        jButton4.setEnabled(true);
                        jButton5.setEnabled(true);
                        jButton6.setEnabled(true);
                        jButton7.setEnabled(true);
                        jButton8.setEnabled(true);
                        jButton9.setEnabled(true);
                    }
                } else {
                    if (s.equals("1")) {
                        ImageIcon icon;

                        if (currentPlayer == 1) {
                            icon = new ImageIcon("src//silang.png");
                            
                            playerBtn1 = "x";
                            
                        } else {
                            icon = new ImageIcon("src//lingkaran.png");
                            playerBtn1 = "o";
                        }
                        jButton1.setIcon(icon);
                        btn1 = 1;
                        setEnable();
                        
                        menang();
                        
                    } else if (s.equals("2")) {
                        ImageIcon icon;

                        if (currentPlayer == 1) {
                            icon = new ImageIcon("src//silang.png");
                            playerBtn2 = "x";
                        } else {
                            icon = new ImageIcon("src//lingkaran.png");
                            playerBtn2 = "o";
                        }
                        jButton2.setIcon(icon);
                        btn2 = 1;
                        setEnable();
                        
                        menang();
                    } else if (s.equals("3")) {
                        ImageIcon icon;

                        if (currentPlayer == 1) {
                            icon = new ImageIcon("src//silang.png");
                            playerBtn3 = "x";
                        } else {
                            icon = new ImageIcon("src//lingkaran.png");
                            playerBtn3 = "o";
                        }
                        jButton3.setIcon(icon);
                        btn3 = 1;
                        setEnable();
                        
                        menang();
                    } else if (s.equals("4")) {
                        ImageIcon icon;

                        if (currentPlayer == 1) {
                            icon = new ImageIcon("src//silang.png");
                            playerBtn4 = "x";
                        } else {
                            icon = new ImageIcon("src//lingkaran.png");
                            playerBtn4 = "o";
                        }
                        jButton4.setIcon(icon);
                        btn4 = 1;
                        setEnable();
                        menang();
                    } else if (s.equals("5")) {
                        ImageIcon icon;

                        if (currentPlayer == 1) {
                            icon = new ImageIcon("src//silang.png");
                            playerBtn5 = "x";
                        } else {
                            icon = new ImageIcon("src//lingkaran.png");
                            playerBtn5 = "o";
                        }
                        jButton5.setIcon(icon);
                        btn5 = 1;
                        setEnable();
                        menang();
                    } else if (s.equals("6")) {
                        ImageIcon icon;

                        if (currentPlayer == 1) {
                            icon = new ImageIcon("src//silang.png");
                            playerBtn6 = "x";
                        } else {
                            icon = new ImageIcon("src//lingkaran.png");
                            playerBtn6 = "o";
                        }
                        jButton6.setIcon(icon);
                        btn6 = 1;
                        setEnable();
                         menang();
                    } else if (s.equals("7")) {
                        ImageIcon icon;

                        if (currentPlayer == 1) {
                            icon = new ImageIcon("src//silang.png");
                            playerBtn7 = "x";
                        } else {
                            icon = new ImageIcon("src//lingkaran.png");
                            playerBtn7 = "o";
                        }
                        jButton7.setIcon(icon);
                        btn7 = 1;
                        setEnable();
                        
                        menang();
                    } else if (s.equals("8")) {
                        ImageIcon icon;

                        if (currentPlayer == 1) {
                            icon = new ImageIcon("src//silang.png");
                            playerBtn8 = "x";
                        } else {
                            icon = new ImageIcon("src//lingkaran.png");
                            playerBtn8 = "o";
                        }
                        jButton8.setIcon(icon);
                        btn8 = 1;
                        setEnable();
                        
                        menang();
                    } else {
                        ImageIcon icon;

                        if (currentPlayer == 1) {
                            icon = new ImageIcon("src//silang.png");
                            playerBtn9 = "x";
                        } else {
                            icon = new ImageIcon("src//lingkaran.png");
                            playerBtn9 = "o";
                        }
                        jButton9.setIcon(icon);
                        btn9 = 1;
                        setEnable();
                        
                        menang();
                    }
                }
            }

        } catch (IOException e) {
            System.err.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel hasilSuit;
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private static javax.swing.JButton jButton4;
    private static javax.swing.JButton jButton5;
    private static javax.swing.JButton jButton6;
    private static javax.swing.JButton jButton7;
    private static javax.swing.JButton jButton8;
    private static javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
